source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RYFPSLabel_Example', :exclusive => true do
  pod "RYFPSLabel", :path => "../"
end

target 'RYFPSLabel_Tests', :exclusive => true do
  pod "RYFPSLabel", :path => "../"

  
end
